version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    parameters:
      python-version:
        type: string
    executor:
      name: win/default
      size: "medium"
      shell: bash.exe

    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run:
          name: Set up conda
          command: |
            conda config --set always_yes yes --set changeps1 no
            conda update -q conda
            conda install -y -q -c conda-forge mamba --quiet
      - run:
          name: Create vaex-dex environment
          command: |
            mamba create -y -q -c conda-forge -n vaex-dev python=<< parameters.python-version >> compilers --quiet
            source activate vaex-dev
            mamba env update --file ci/conda-env.yml  --quiet
            conda list
      - run:
          name: Install vaex
          command: |
            pip install pcre
            pip install -e . -v

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          matrix:
            parameters:
              python-version: ["3.8"]